[package]
name = "codegen"
version = "0.1.0"
license.workspace = true
edition = "2021"
publish = false

[[bin]]
name = "codegen"
path = "main.rs"

[dependencies]
phf_codegen = "0.11.3"
itertools = "0.14"
